/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import t2poo.Curso;
import t2poo.Estudiante;

/**
 *
 * @author USER
 */
public class VentanaCursos extends javax.swing.JFrame {

    private Curso[] cursos = new Curso[3];
    /**
     * Creates new form VentanaCursos
     */
    public VentanaCursos() {
        initComponents();
    }
    
    public VentanaCursos(Curso[] cursos) {
        this.cursos = cursos;
        initComponents();
        lbl_mañana.setText(this.cursos[0].getTitulo());
        lbl_tarde.setText(this.cursos[1].getTitulo());
        lbl_noche.setText(this.cursos[2].getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_noche = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_tarde = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_mañana = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_noche.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_noche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_noche.setText("-");
        lbl_noche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nocheMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_noche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BIENVENIDO MARIO PEREZ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lbl_tarde.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tarde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tarde.setText("-");
        lbl_tarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tardeMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_tarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbl_mañana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_mañana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mañana.setText("-");
        lbl_mañana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_mañanaMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_mañana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecBlanco.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo.png"))); // NOI18N
        jPanel1.add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_mañanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mañanaMouseClicked
        Estudiante[] arregloEstudiantes = new Estudiante[10];
        
        for (int i = 0; i < arregloEstudiantes.length; i++) {
            Estudiante estudiante = new Estudiante(); 
            switch (i) {
                case 0:
                    estudiante.setNombre(" ANDY ERNESTO MARMOLEJO");
                    break;
                case 1:
                    estudiante.setNombre(" ANGHY NICOLE VELASQUEZ");
                    break;
                case 2:
                    estudiante.setNombre(" CRISTHIAN AXEL CISNEROS");
                    break;
                case 3:
                    estudiante.setNombre(" ESTHUARD EDUARDO ZULETA");
                    break;
                case 4:
                    estudiante.setNombre(" GERALDIN ANABEL RIVERA");
                    break;
                case 5:
                    estudiante.setNombre(" HECTOR LEONARDO DE LA CRUZ");
                    break;
                case 6:
                    estudiante.setNombre(" JAIME EUSEBIO TINOCO JARA");
                    break;
                case 7:
                    estudiante.setNombre(" JOEL QUISPE ANDIA");
                    break;
                case 8:
                    estudiante.setNombre(" JOSUE CRISTHOFER VIVANCO");
                    break;
                case 9:
                    estudiante.setNombre(" DENIS OMAR REYNA MEDINA");
                    break;
                default:                    
                    break;
            }
            arregloEstudiantes[i] = estudiante; 
        }
        this.cursos[0].setEstudiantesEnElCurso(arregloEstudiantes);
        
        mostrarVentana(cursos[0]);
    }//GEN-LAST:event_lbl_mañanaMouseClicked

    private void lbl_tardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tardeMouseClicked
        Estudiante[] arregloEstudiantes = new Estudiante[10];
        
        for (int i = 0; i < arregloEstudiantes.length; i++) {
            Estudiante estudiante = new Estudiante(); 
            switch (i) {
                case 0:
                    estudiante.setNombre(" HECTOR LEONARDO DE LA CRUZ");
                    break;
                case 1:
                    estudiante.setNombre(" CRISTHIAN AXEL CISNEROS");
                    break;
                case 2:
                    estudiante.setNombre(" JOSUE CRISTHOFER VIVANCO");
                    break;
                case 3:
                    estudiante.setNombre(" ESTHUARD EDUARDO ZULETA");
                    break;
                case 4:
                    estudiante.setNombre(" JAIME EUSEBIO TINOCO JARA");
                    break;
                case 5:
                    estudiante.setNombre(" ANDY ERNESTO MARMOLEJO");
                    break;
                case 6:
                    estudiante.setNombre(" ANGHY NICOLE VELASQUEZ");
                    break;
                case 7:
                    estudiante.setNombre(" JOEL QUISPE ANDIA");
                    break;
                case 8:
                    estudiante.setNombre(" GERALDIN ANABEL RIVERA");
                    break;
                case 9:
                    estudiante.setNombre(" DENIS OMAR REYNA MEDINA");
                    break;
                default:                    
                    break;
            }
            arregloEstudiantes[i] = estudiante; 
        }
        this.cursos[1].setEstudiantesEnElCurso(arregloEstudiantes);
        
        mostrarVentana(cursos[1]);
    }//GEN-LAST:event_lbl_tardeMouseClicked

    private void lbl_nocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nocheMouseClicked
        Estudiante[] arregloEstudiantes = new Estudiante[10];
        
        for (int i = 0; i < arregloEstudiantes.length; i++) {
            Estudiante estudiante = new Estudiante(); 
            switch (i) {
                case 0:
                    estudiante.setNombre(" GERALDIN ANABEL RIVERA");
                    break;
                case 1:
                    estudiante.setNombre(" CRISTHIAN AXEL CISNEROS");
                    break;
                case 2:
                    estudiante.setNombre(" HECTOR LEONARDO DE LA CRUZ");
                    break;
                case 3:
                    estudiante.setNombre(" ESTHUARD EDUARDO ZULETA");
                    break;
                case 4:
                    estudiante.setNombre(" JOSUE CRISTHOFER VIVANCO");
                    break;
                case 5:
                    estudiante.setNombre(" ANDY ERNESTO MARMOLEJO");
                    break;
                case 6:
                    estudiante.setNombre(" JAIME EUSEBIO TINOCO JARA");
                    break;
                case 7:
                    estudiante.setNombre(" JOEL QUISPE ANDIA");
                    break;
                case 8:
                    estudiante.setNombre(" ANGHY NICOLE VELASQUEZ");
                    break;
                case 9:
                    estudiante.setNombre(" DENIS OMAR REYNA MEDINA");
                    break;
                default:                    
                    break;
            }
            arregloEstudiantes[i] = estudiante; 
        }
        this.cursos[2].setEstudiantesEnElCurso(arregloEstudiantes);
        
        mostrarVentana(cursos[2]);
    }//GEN-LAST:event_lbl_nocheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCursos().setVisible(true);
            }
        });
    }
    
    private void mostrarVentana(Curso curso){
        VentanaTomarAsistencia ventanaTomarAsistencia = new
            VentanaTomarAsistencia(curso, this);
        ventanaTomarAsistencia.setLocationRelativeTo(this);
        this.setVisible(false);
        ventanaTomarAsistencia.setVisible(true);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_mañana;
    private javax.swing.JLabel lbl_noche;
    private javax.swing.JLabel lbl_tarde;
    // End of variables declaration//GEN-END:variables
}
