/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import t2poo.Curso;
import t2poo.reporteDeAsistencia;

/**
 *
 * @author USER
 */
public class VentanaVerRegistros extends javax.swing.JFrame {
    private DefaultListModel<String> modeloNombres = new DefaultListModel<>();
    
    Curso cursoSelec;
    VentanaTomarAsistencia ventanaAnterior;
    /**
     * Creates new form VentanaCursos
     */
    public VentanaVerRegistros() {
        initComponents();
    }
    public VentanaVerRegistros(Curso curso, VentanaTomarAsistencia padre) {
        ventanaAnterior = padre;
        cursoSelec = curso;
        initComponents();
        lbl_titulo.setText(curso.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMostrando = new javax.swing.JList<>();
        lbl_FlechaAtras = new javax.swing.JLabel();
        lbl_CuaAtras = new javax.swing.JLabel();
        lbl_iconVer = new javax.swing.JLabel();
        lbl_CuaCeleste = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("CURSO SELECCIONADO");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        listaMostrando.setBackground(new java.awt.Color(204, 204, 204));
        listaMostrando.setBorder(null);
        listaMostrando.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        listaMostrando.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(listaMostrando);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, -1));

        lbl_FlechaAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_FlechaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconAtras.png"))); // NOI18N
        lbl_FlechaAtras.setToolTipText("");
        lbl_FlechaAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_FlechaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_FlechaAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_FlechaAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_FlechaAtrasMouseExited(evt);
            }
        });
        jPanel1.add(lbl_FlechaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 30));

        lbl_CuaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaBlanco.png"))); // NOI18N
        jPanel1.add(lbl_CuaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lbl_iconVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_iconVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconVer.png"))); // NOI18N
        lbl_iconVer.setToolTipText("");
        lbl_iconVer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_iconVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_iconVerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_iconVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_iconVerMouseExited(evt);
            }
        });
        jPanel1.add(lbl_iconVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 30, 30));

        lbl_CuaCeleste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaCeleste.png"))); // NOI18N
        jPanel1.add(lbl_CuaCeleste, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo.png"))); // NOI18N
        jPanel1.add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_FlechaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FlechaAtrasMouseClicked
        ventanaAnterior.setLocationRelativeTo(this);
        this.setVisible(false);
        ventanaAnterior.setVisible(true);  
    }//GEN-LAST:event_lbl_FlechaAtrasMouseClicked

    private void lbl_iconVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_iconVerMouseClicked
        if (listaMostrando.getComponentCount() - 3 == -2) {
            JOptionPane.showMessageDialog(this, 
                    "No hay ningún registro!", "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int index = listaMostrando.getSelectedIndex();    
        
        if (index == -1) {
            JOptionPane.showMessageDialog(this, 
                    "No ha seleccionado ningún registro!", "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        reporteDeAsistencia repSelec =  cursoSelec
                .getListaDeReportesDeAsistencia().get(index);    
        
        VentanaVerAsistencias ventanaVerAsistencias = 
                new VentanaVerAsistencias(cursoSelec, this);
        ventanaVerAsistencias.setLocationRelativeTo(this);
        ventanaVerAsistencias.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_lbl_iconVerMouseClicked

    private void lbl_iconVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_iconVerMouseEntered
        lbl_CuaCeleste.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/Imgs/CuaCelesteO.png")));
    }//GEN-LAST:event_lbl_iconVerMouseEntered

    private void lbl_iconVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_iconVerMouseExited
        lbl_CuaCeleste.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/Imgs/CuaCeleste.png")));
    }//GEN-LAST:event_lbl_iconVerMouseExited

    private void lbl_FlechaAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FlechaAtrasMouseEntered
        lbl_CuaAtras.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/Imgs/CuaBlancoO.png")));
    }//GEN-LAST:event_lbl_FlechaAtrasMouseEntered

    private void lbl_FlechaAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FlechaAtrasMouseExited
        lbl_CuaAtras.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/Imgs/CuaBlanco.png")));
    }//GEN-LAST:event_lbl_FlechaAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVerRegistros().setVisible(true);
            }
        });
    }
    
    public void TenerListaActualizada(){
        listaMostrando.removeAll();
        modeloNombres.removeAllElements();
        
        for (reporteDeAsistencia rep : cursoSelec.getListaDeReportesDeAsistencia()) {
            String MostrarEst = rep.getTitulo();         
            String nombreString = MostrarEst;
            
            modeloNombres.addElement(nombreString);
            listaMostrando.setModel(modeloNombres);            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_CuaAtras;
    private javax.swing.JLabel lbl_CuaCeleste;
    private javax.swing.JLabel lbl_FlechaAtras;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_iconVer;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JList<String> listaMostrando;
    // End of variables declaration//GEN-END:variables
}
