/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import t2poo.Curso;
import t2poo.Estudiante;

/**
 *
 * @author USER
 */
public class VentanaVerAsistencias extends javax.swing.JFrame {

    Curso cursoSelec;
    VentanaVerRegistros ventanaAnterior;
    Estudiante[] estudiantes = new Estudiante[10];
    
    /**
     * Creates new form VentanaCursos
     */
    public VentanaVerAsistencias() {
        initComponents();
    }
    
    public VentanaVerAsistencias(Curso curso, VentanaVerRegistros padre) {
        ventanaAnterior = padre;
        cursoSelec = curso;
        estudiantes = curso.getEstudiantesEnElCurso();
        initComponents();
        lbl_titulo.setText(curso.getTitulo());
        lbl_Estudiante1.setText(estudiantes[0].getNombre());
        lbl_Estudiante2.setText(estudiantes[1].getNombre());
        lbl_Estudiante3.setText(estudiantes[2].getNombre());
        lbl_Estudiante4.setText(estudiantes[3].getNombre());
        lbl_Estudiante5.setText(estudiantes[4].getNombre());
        lbl_Estudiante6.setText(estudiantes[5].getNombre());
        lbl_Estudiante7.setText(estudiantes[6].getNombre());
        lbl_Estudiante8.setText(estudiantes[7].getNombre());
        lbl_Estudiante9.setText(estudiantes[8].getNombre());
        lbl_Estudiante10.setText(estudiantes[9].getNombre()); 
        lbl_est1.setText(estudiantes[0].getEstAsistencia());
        lbl_est2.setText(estudiantes[1].getEstAsistencia());
        lbl_est3.setText(estudiantes[2].getEstAsistencia());
        lbl_est4.setText(estudiantes[3].getEstAsistencia());
        lbl_est5.setText(estudiantes[4].getEstAsistencia());
        lbl_est6.setText(estudiantes[5].getEstAsistencia());
        lbl_est7.setText(estudiantes[6].getEstAsistencia());
        lbl_est8.setText(estudiantes[7].getEstAsistencia());
        lbl_est9.setText(estudiantes[8].getEstAsistencia());
        lbl_est10.setText(estudiantes[9].getEstAsistencia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Estudiante6 = new javax.swing.JLabel();
        lbl_Estudiante5 = new javax.swing.JLabel();
        lbl_Estudiante2 = new javax.swing.JLabel();
        lbl_Estudiante8 = new javax.swing.JLabel();
        lbl_Estudiante4 = new javax.swing.JLabel();
        lbl_Estudiante3 = new javax.swing.JLabel();
        lbl_Estudiante9 = new javax.swing.JLabel();
        lbl_est1 = new javax.swing.JLabel();
        lbl_Estudiante10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_Estudiante1 = new javax.swing.JLabel();
        lbl_Estudiante7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_est2 = new javax.swing.JLabel();
        lbl_est3 = new javax.swing.JLabel();
        lbl_est4 = new javax.swing.JLabel();
        lbl_est5 = new javax.swing.JLabel();
        lbl_est6 = new javax.swing.JLabel();
        lbl_est7 = new javax.swing.JLabel();
        lbl_est8 = new javax.swing.JLabel();
        lbl_est9 = new javax.swing.JLabel();
        lbl_est10 = new javax.swing.JLabel();
        lbl_FlechaAtras = new javax.swing.JLabel();
        lbl_CuaAtras = new javax.swing.JLabel();
        lbl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Estudiante6.setText("jLabel13");
        jPanel1.add(lbl_Estudiante6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 20));

        lbl_Estudiante5.setText("jLabel13");
        jPanel1.add(lbl_Estudiante5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 20));

        lbl_Estudiante2.setText("jLabel13");
        jPanel1.add(lbl_Estudiante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 20));

        lbl_Estudiante8.setText("jLabel13");
        jPanel1.add(lbl_Estudiante8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 20));

        lbl_Estudiante4.setText("jLabel13");
        jPanel1.add(lbl_Estudiante4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 20));

        lbl_Estudiante3.setText("jLabel13");
        jPanel1.add(lbl_Estudiante3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 20));

        lbl_Estudiante9.setText("jLabel13");
        jPanel1.add(lbl_Estudiante9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 20));

        lbl_est1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est1.setText("F");
        lbl_est1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 20, 20));

        lbl_Estudiante10.setText("jLabel13");
        jPanel1.add(lbl_Estudiante10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lbl_Estudiante1.setText("jLabel13");
        jPanel1.add(lbl_Estudiante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 20));

        lbl_Estudiante7.setText("jLabel13");
        jPanel1.add(lbl_Estudiante7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/RecGris.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("REGISTRO N");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("ESTUDIANTES");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("EST.");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        lbl_est2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est2.setText("F");
        lbl_est2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 20, 20));

        lbl_est3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est3.setText("F");
        lbl_est3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 20, 20));

        lbl_est4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est4.setText("F");
        lbl_est4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 20, 20));

        lbl_est5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est5.setText("F");
        lbl_est5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 20, 20));

        lbl_est6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est6.setText("F");
        lbl_est6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 20, 20));

        lbl_est7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est7.setText("F");
        lbl_est7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 20, 20));

        lbl_est8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est8.setText("F");
        lbl_est8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 20, 20));

        lbl_est9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est9.setText("F");
        lbl_est9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 20, 20));

        lbl_est10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_est10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_est10.setText("F");
        lbl_est10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_est10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 20, 20));

        lbl_FlechaAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_FlechaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/iconAtras.png"))); // NOI18N
        lbl_FlechaAtras.setToolTipText("");
        lbl_FlechaAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_FlechaAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_FlechaAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_FlechaAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_FlechaAtrasMouseExited(evt);
            }
        });
        jPanel1.add(lbl_FlechaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 30, 30));

        lbl_CuaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/CuaBlanco.png"))); // NOI18N
        jPanel1.add(lbl_CuaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lbl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo.png"))); // NOI18N
        jPanel1.add(lbl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_FlechaAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FlechaAtrasMouseClicked
        ventanaAnterior.setLocationRelativeTo(this);
        this.setVisible(false);
        ventanaAnterior.setVisible(true); 
    }//GEN-LAST:event_lbl_FlechaAtrasMouseClicked

    private void lbl_FlechaAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FlechaAtrasMouseEntered
        lbl_CuaAtras.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/Imgs/CuaBlancoO.png")));
    }//GEN-LAST:event_lbl_FlechaAtrasMouseEntered

    private void lbl_FlechaAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FlechaAtrasMouseExited
        lbl_CuaAtras.setIcon(new javax.swing.ImageIcon(getClass()
                .getResource("/Imgs/CuaBlanco.png")));
    }//GEN-LAST:event_lbl_FlechaAtrasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVerAsistencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_CuaAtras;
    private javax.swing.JLabel lbl_Estudiante1;
    private javax.swing.JLabel lbl_Estudiante10;
    private javax.swing.JLabel lbl_Estudiante2;
    private javax.swing.JLabel lbl_Estudiante3;
    private javax.swing.JLabel lbl_Estudiante4;
    private javax.swing.JLabel lbl_Estudiante5;
    private javax.swing.JLabel lbl_Estudiante6;
    private javax.swing.JLabel lbl_Estudiante7;
    private javax.swing.JLabel lbl_Estudiante8;
    private javax.swing.JLabel lbl_Estudiante9;
    private javax.swing.JLabel lbl_FlechaAtras;
    private javax.swing.JLabel lbl_Fondo;
    private javax.swing.JLabel lbl_est1;
    private javax.swing.JLabel lbl_est10;
    private javax.swing.JLabel lbl_est2;
    private javax.swing.JLabel lbl_est3;
    private javax.swing.JLabel lbl_est4;
    private javax.swing.JLabel lbl_est5;
    private javax.swing.JLabel lbl_est6;
    private javax.swing.JLabel lbl_est7;
    private javax.swing.JLabel lbl_est8;
    private javax.swing.JLabel lbl_est9;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
